package com.autolight.entity;

import java.util.Date;

public class Asklight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_asklight.asklight_id
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    private Integer asklight_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_asklight.room_name
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    private String room_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_asklight.user_id
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_asklight.user_name
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_asklight.asklight_text
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    private String asklight_text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_asklight.asklight_time
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    private Date asklight_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_asklight.asklight_id
     *
     * @return the value of tb_asklight.asklight_id
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public Integer getAsklight_id() {
        return asklight_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_asklight.asklight_id
     *
     * @param asklight_id the value for tb_asklight.asklight_id
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public void setAsklight_id(Integer asklight_id) {
        this.asklight_id = asklight_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_asklight.room_name
     *
     * @return the value of tb_asklight.room_name
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public String getRoom_name() {
        return room_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_asklight.room_name
     *
     * @param room_name the value for tb_asklight.room_name
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public void setRoom_name(String room_name) {
        this.room_name = room_name == null ? null : room_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_asklight.user_id
     *
     * @return the value of tb_asklight.user_id
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_asklight.user_id
     *
     * @param user_id the value for tb_asklight.user_id
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_asklight.user_name
     *
     * @return the value of tb_asklight.user_name
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_asklight.user_name
     *
     * @param user_name the value for tb_asklight.user_name
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_asklight.asklight_text
     *
     * @return the value of tb_asklight.asklight_text
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public String getAsklight_text() {
        return asklight_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_asklight.asklight_text
     *
     * @param asklight_text the value for tb_asklight.asklight_text
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public void setAsklight_text(String asklight_text) {
        this.asklight_text = asklight_text == null ? null : asklight_text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_asklight.asklight_time
     *
     * @return the value of tb_asklight.asklight_time
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public Date getAsklight_time() {
        return asklight_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_asklight.asklight_time
     *
     * @param asklight_time the value for tb_asklight.asklight_time
     *
     * @mbg.generated Mon Mar 30 16:36:45 CST 2020
     */
    public void setAsklight_time(Date asklight_time) {
        this.asklight_time = asklight_time;
    }
}