package com.autolight.entity;

import java.util.ArrayList;
import java.util.List;

public class LighttypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public LighttypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLtype_idIsNull() {
            addCriterion("ltype_id is null");
            return (Criteria) this;
        }

        public Criteria andLtype_idIsNotNull() {
            addCriterion("ltype_id is not null");
            return (Criteria) this;
        }

        public Criteria andLtype_idEqualTo(Integer value) {
            addCriterion("ltype_id =", value, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idNotEqualTo(Integer value) {
            addCriterion("ltype_id <>", value, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idGreaterThan(Integer value) {
            addCriterion("ltype_id >", value, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("ltype_id >=", value, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idLessThan(Integer value) {
            addCriterion("ltype_id <", value, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idLessThanOrEqualTo(Integer value) {
            addCriterion("ltype_id <=", value, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idIn(List<Integer> values) {
            addCriterion("ltype_id in", values, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idNotIn(List<Integer> values) {
            addCriterion("ltype_id not in", values, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idBetween(Integer value1, Integer value2) {
            addCriterion("ltype_id between", value1, value2, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLtype_idNotBetween(Integer value1, Integer value2) {
            addCriterion("ltype_id not between", value1, value2, "ltype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idIsNull() {
            addCriterion("lighttype_id is null");
            return (Criteria) this;
        }

        public Criteria andLighttype_idIsNotNull() {
            addCriterion("lighttype_id is not null");
            return (Criteria) this;
        }

        public Criteria andLighttype_idEqualTo(Integer value) {
            addCriterion("lighttype_id =", value, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idNotEqualTo(Integer value) {
            addCriterion("lighttype_id <>", value, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idGreaterThan(Integer value) {
            addCriterion("lighttype_id >", value, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("lighttype_id >=", value, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idLessThan(Integer value) {
            addCriterion("lighttype_id <", value, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idLessThanOrEqualTo(Integer value) {
            addCriterion("lighttype_id <=", value, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idIn(List<Integer> values) {
            addCriterion("lighttype_id in", values, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idNotIn(List<Integer> values) {
            addCriterion("lighttype_id not in", values, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idBetween(Integer value1, Integer value2) {
            addCriterion("lighttype_id between", value1, value2, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_idNotBetween(Integer value1, Integer value2) {
            addCriterion("lighttype_id not between", value1, value2, "lighttype_id");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameIsNull() {
            addCriterion("lighttype_name is null");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameIsNotNull() {
            addCriterion("lighttype_name is not null");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameEqualTo(String value) {
            addCriterion("lighttype_name =", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameNotEqualTo(String value) {
            addCriterion("lighttype_name <>", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameGreaterThan(String value) {
            addCriterion("lighttype_name >", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameGreaterThanOrEqualTo(String value) {
            addCriterion("lighttype_name >=", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameLessThan(String value) {
            addCriterion("lighttype_name <", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameLessThanOrEqualTo(String value) {
            addCriterion("lighttype_name <=", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameLike(String value) {
            addCriterion("lighttype_name like", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameNotLike(String value) {
            addCriterion("lighttype_name not like", value, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameIn(List<String> values) {
            addCriterion("lighttype_name in", values, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameNotIn(List<String> values) {
            addCriterion("lighttype_name not in", values, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameBetween(String value1, String value2) {
            addCriterion("lighttype_name between", value1, value2, "lighttype_name");
            return (Criteria) this;
        }

        public Criteria andLighttype_nameNotBetween(String value1, String value2) {
            addCriterion("lighttype_name not between", value1, value2, "lighttype_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_lighttype
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 26 16:10:56 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_lighttype
     *
     * @mbg.generated Thu Mar 26 16:10:56 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}