package com.autolight.entity;

import java.util.ArrayList;
import java.util.List;

public class ReplytypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public ReplytypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReply_idIsNull() {
            addCriterion("reply_id is null");
            return (Criteria) this;
        }

        public Criteria andReply_idIsNotNull() {
            addCriterion("reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andReply_idEqualTo(Integer value) {
            addCriterion("reply_id =", value, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idNotEqualTo(Integer value) {
            addCriterion("reply_id <>", value, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idGreaterThan(Integer value) {
            addCriterion("reply_id >", value, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("reply_id >=", value, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idLessThan(Integer value) {
            addCriterion("reply_id <", value, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idLessThanOrEqualTo(Integer value) {
            addCriterion("reply_id <=", value, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idIn(List<Integer> values) {
            addCriterion("reply_id in", values, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idNotIn(List<Integer> values) {
            addCriterion("reply_id not in", values, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idBetween(Integer value1, Integer value2) {
            addCriterion("reply_id between", value1, value2, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReply_idNotBetween(Integer value1, Integer value2) {
            addCriterion("reply_id not between", value1, value2, "reply_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idIsNull() {
            addCriterion("replytype_id is null");
            return (Criteria) this;
        }

        public Criteria andReplytype_idIsNotNull() {
            addCriterion("replytype_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplytype_idEqualTo(Integer value) {
            addCriterion("replytype_id =", value, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idNotEqualTo(Integer value) {
            addCriterion("replytype_id <>", value, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idGreaterThan(Integer value) {
            addCriterion("replytype_id >", value, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("replytype_id >=", value, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idLessThan(Integer value) {
            addCriterion("replytype_id <", value, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idLessThanOrEqualTo(Integer value) {
            addCriterion("replytype_id <=", value, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idIn(List<Integer> values) {
            addCriterion("replytype_id in", values, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idNotIn(List<Integer> values) {
            addCriterion("replytype_id not in", values, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idBetween(Integer value1, Integer value2) {
            addCriterion("replytype_id between", value1, value2, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_idNotBetween(Integer value1, Integer value2) {
            addCriterion("replytype_id not between", value1, value2, "replytype_id");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameIsNull() {
            addCriterion("replytype_name is null");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameIsNotNull() {
            addCriterion("replytype_name is not null");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameEqualTo(String value) {
            addCriterion("replytype_name =", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameNotEqualTo(String value) {
            addCriterion("replytype_name <>", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameGreaterThan(String value) {
            addCriterion("replytype_name >", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameGreaterThanOrEqualTo(String value) {
            addCriterion("replytype_name >=", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameLessThan(String value) {
            addCriterion("replytype_name <", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameLessThanOrEqualTo(String value) {
            addCriterion("replytype_name <=", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameLike(String value) {
            addCriterion("replytype_name like", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameNotLike(String value) {
            addCriterion("replytype_name not like", value, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameIn(List<String> values) {
            addCriterion("replytype_name in", values, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameNotIn(List<String> values) {
            addCriterion("replytype_name not in", values, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameBetween(String value1, String value2) {
            addCriterion("replytype_name between", value1, value2, "replytype_name");
            return (Criteria) this;
        }

        public Criteria andReplytype_nameNotBetween(String value1, String value2) {
            addCriterion("replytype_name not between", value1, value2, "replytype_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_replytype
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 28 14:31:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_replytype
     *
     * @mbg.generated Sat Mar 28 14:31:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}