package com.autolight.entity;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room.room_id
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    private Integer room_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room.room_name
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    private String room_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room.room_lightquantity
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    private Integer room_lightquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_room.dianlustatus_name
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    private String dianlustatus_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room.room_id
     *
     * @return the value of tb_room.room_id
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public Integer getRoom_id() {
        return room_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room.room_id
     *
     * @param room_id the value for tb_room.room_id
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public void setRoom_id(Integer room_id) {
        this.room_id = room_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room.room_name
     *
     * @return the value of tb_room.room_name
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public String getRoom_name() {
        return room_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room.room_name
     *
     * @param room_name the value for tb_room.room_name
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public void setRoom_name(String room_name) {
        this.room_name = room_name == null ? null : room_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room.room_lightquantity
     *
     * @return the value of tb_room.room_lightquantity
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public Integer getRoom_lightquantity() {
        return room_lightquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room.room_lightquantity
     *
     * @param room_lightquantity the value for tb_room.room_lightquantity
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public void setRoom_lightquantity(Integer room_lightquantity) {
        this.room_lightquantity = room_lightquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_room.dianlustatus_name
     *
     * @return the value of tb_room.dianlustatus_name
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public String getDianlustatus_name() {
        return dianlustatus_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_room.dianlustatus_name
     *
     * @param dianlustatus_name the value for tb_room.dianlustatus_name
     *
     * @mbg.generated Tue Mar 31 13:42:16 CST 2020
     */
    public void setDianlustatus_name(String dianlustatus_name) {
        this.dianlustatus_name = dianlustatus_name == null ? null : dianlustatus_name.trim();
    }
}