package com.autolight.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_gender
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    private String user_gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_phone
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    private String user_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_password
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    private String user_password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param user_id the value for tb_user.user_id
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param user_name the value for tb_user.user_name
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_gender
     *
     * @return the value of tb_user.user_gender
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public String getUser_gender() {
        return user_gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_gender
     *
     * @param user_gender the value for tb_user.user_gender
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public void setUser_gender(String user_gender) {
        this.user_gender = user_gender == null ? null : user_gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_phone
     *
     * @return the value of tb_user.user_phone
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public String getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_phone
     *
     * @param user_phone the value for tb_user.user_phone
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public void setUser_phone(String user_phone) {
        this.user_phone = user_phone == null ? null : user_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_password
     *
     * @return the value of tb_user.user_password
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public String getUser_password() {
        return user_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_password
     *
     * @param user_password the value for tb_user.user_password
     *
     * @mbg.generated Wed Mar 18 21:18:20 CST 2020
     */
    public void setUser_password(String user_password) {
        this.user_password = user_password == null ? null : user_password.trim();
    }
}